---
galaxy_info:
  author: Ansible Middleware Team
  description: Create and manage the systemd service unit for Open Liberty
  license: GPL-2.0-only
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
  galaxy_tags:
    - openliberty
    - liberty
    - systemd
    - java
    - middleware
    - ibm
dependencies: []
