---
galaxy_info:
  author: Ansible Middleware Team
  description: Render and deploy server.xml and related configuration for Open Liberty
  license: GPL-2.0-only
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
  galaxy_tags:
    - openliberty
    - liberty
    - java
    - jakarta
    - middleware
    - ibm
dependencies: []
