---
galaxy_info:
  author: Ansible-Middleware Team
  description: Validate that Open Liberty is running and healthy
  license: GPL-2.0-only
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
        - "10"
  galaxy_tags:
    - openliberty
    - liberty
    - java
    - middleware
dependencies: []
