<!doctype html>
<html>
  <head>
    <title>Open Liberty Ansible Collection documentation index</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="main/_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="main/_static/css/theme.css" type="text/css" />
    <link rel="stylesheet" href="main/_static/ansible-basic-sphinx-ext.css" type="text/css" />
    <script data-url_root="./" id="documentation_options" src="main/_static/documentation_options.js"></script>
    <script src="main/_static/jquery.js"></script>
    <script src="main/_static/underscore.js"></script>
    <script src="main/_static/doctools.js"></script>
    <script src="main/_static/js/theme.js"></script>
  </head>

<body class="wy-body-for-nav">
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
            <a href="#" class="icon icon-home"> Open Liberty Ansible Collection</a>
        </div>
        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
          <p class="caption" role="heading"><span class="caption-text">Middleware Automation</span></p>
          <ul>
            <li class="toctree-l1"><a class="reference internal" href="https://ansible-middleware.github.io/infinispan/">Infinispan / Red Hat Data Grid</a></li>
            <li class="toctree-l1"><a class="reference internal" href="https://ansible-middleware.github.io/keycloak/">Keycloak / Red Hat Single Sign-On</a></li>
            <li class="toctree-l1"><a class="reference internal" href="https://ansible-middleware.github.io/wildfly/">WildFly / Red Hat JBoss EAP</a></li>
            <li class="toctree-l1"><a class="reference internal" href="https://ansible-middleware.github.io/jws/">Tomcat / Red Hat JWS</a></li>
            <li class="toctree-l1"><a class="reference internal" href="https://ansible-middleware.github.io/amq/">ActiveMQ / Red Hat AMQ</a></li>
            <li class="toctree-l1"><a class="reference internal" href="https://ansible-middleware.github.io/amq_streams/">Kafka / Red Hat AMQ Streams</a></li>
            <li class="toctree-l1"><a class="reference internal" href="https://ansible-middleware.github.io/open-liberty/">Open Liberty</a></li>
            <li class="toctree-l1"><a class="reference internal" href="https://ansible-middleware.github.io/common/">Ansible Middleware utilities</a></li>
            <li class="toctree-l1"><a class="reference internal" href="https://ansible-middleware.github.io/ansible_collections_jcliff/">JCliff</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">
      <div class="wy-nav-content">
          <div class="rst-content">
            <div role="navigation" aria-label="Page navigation">
              <ul class="wy-breadcrumbs">
                  <li><a href="#" class="icon icon-home"></a> &raquo;</li>
                  <li>Welcome to Open Liberty Collection documentation</li>
                  <li class="wy-breadcrumbs-aside"></li>
              </ul>
              <hr/>
            </div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
             <div itemprop="articleBody">
                <section id="welcome-to-open-liberty-collection-documentation">
                  <h1>Welcome to Open Liberty Collection documentation<a class="headerlink" href="#welcome-to-open-liberty-collection-documentation" title="Permalink to this headline"></a></h1>
                    <div class="toctree-wrapper compound">
                      <p class="caption" role="heading"><span class="caption-text">Pick collection version:</span></p>
                        <ul>
